name: CI

on: [pull_request]

jobs:
  lint-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Install Dependencies
        working-directory: site
        run: yarn install --frozen-lockfile

      - name: Run linter
        working-directory: site
        run: yarn lint

  test-gistwsv-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: Install Dependencies
        working-directory: packages/gist-wsv
        run: pnpm install

      - name: Run tests
        working-directory: packages/gist-wsv
        run: pnpm test